In [2]:
#   Import Matplotlib, pandas, and plotly
import pandas as pd 
import plotly as ply
import matplotlib.pyplot as plt
import plotly.express as px

Prepare Data

In [3]:
df1 = pd.read_csv("data/brasil-real-estate-1.csv")
df1.head()

,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd
0,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6443051,-35.7088142",110.0,"$187,230.85"
1,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6430934,-35.70484",65.0,"$81,133.37"
2,house,|Brasil|Alagoas|Maceió|,Northeast,"-9.6227033,-35.7297953",211.0,"$154,465.45"
3,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.622837,-35.719556",99.0,"$146,013.20"
4,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.654955,-35.700227",55.0,"$101,416.71"

In [8]:
#Drop all rows with NaN values from the DataFrame df1.
df1.dropna(inplace=True)

<class 'pandas.core.frame.DataFrame'>
Index: 11551 entries, 0 to 12833
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            11551 non-null  object
 1   place_with_parent_names  11551 non-null  object
 2   region                   11551 non-null  object
 3   lat-lon                  11551 non-null  object
 4   area_m2                  11551 non-null  float64
 5   price_usd                11551 non-null  object
 6   lat                      11551 non-null  object
 7   lon                      11551 non-null  object
dtypes: float64(1), object(7)
memory usage: 812.2+ KB

In [10]:
#Use the "lat-lon" column to create two separate columns in df1: "lat" and "lon". Make sure that the data type for these new columns is float.
df1[["lat", "lon"]] = df1["lat-lon"].str.split(',',expand=True)
# change lat and lon from type object(string) to type float
df1["lat"]=df1.lat.astype(float)
df1["lon"]=df1.lon.astype(float)

In [ ]:
#Use the "place_with_parent_names" column to create a "state" column for df1. 
df1["state"]= df1["place_with_parent_names"].str.split("|", expand= True)[2]

In [27]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11551 entries, 0 to 12833
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            11551 non-null  object
 1   place_with_parent_names  11551 non-null  object
 2   region                   11551 non-null  object
 3   lat-lon                  11551 non-null  object
 4   area_m2                  11551 non-null  float64
 5   price_usd                11551 non-null  float64
 6   lat                      11551 non-null  float64
 7   lon                      11551 non-null  float64
 8   state                    11551 non-null  object
dtypes: float64(4), object(5)
memory usage: 902.4+ KB

In [26]:
#Transform the "price_usd" column of df1 so that all values are floating-point numbers instead of strings
df1["price_usd"]=df1['price_usd'].str.replace("$","", regex=False).str.replace(",","", regex=False).astype(float)

In [32]:
#Drop the "lat-lon" and "place_with_parent_names" columns from df1.
df1= df1.drop(["lat-lon","place_with_parent_names"], axis=1)

In [36]:
#Import the CSV file brasil-real-estate-2.csv into the DataFrame df2.
df2=pd.read_csv("data/brasil-real-estate-2.csv")

In [37]:
df2.head()

,property_type,state,region,lat,lon,area_m2,price_brl
0,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72.0,414222.98
1,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136.0,848408.53
2,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75.0,299438.28
3,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187.0,848408.53
4,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80.0,464129.36

In [40]:
#Use the "price_brl" column to create a new column named "price_usd". When this data was collected in 2015 and 2016, a US dollar cost 3.19 Brazilian reals.
df2["price_usd"]=df2["price_brl"]/3.19

In [41]:
#Drop the "price_brl" column from df2, as well as any rows that have NaN values.
df2.dropna(inplace=True)
df2= df2.drop(["price_brl"], axis=1)

In [43]:
#Concatenate df1 and df2 to create a new DataFrame named df.
df= pd.concat([df1,df2])
print("df shape:", df.shape)

df shape: (22844, 7)